# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "schedule" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"date" VARCHAR NOT NULL,"timeFrom" VARCHAR NOT NULL,"timeTo" VARCHAR NOT NULL,"comment" VARCHAR NOT NULL);
create table "user" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"pass" VARCHAR NOT NULL);

# --- !Downs

drop table "user";
drop table "schedule";

