@startuml
title Iterator Pattern

class Aggregate {
    + {abstract} CreateIterator()
}
class Iterator {
    + {abstract} First()
    + {abstract} Next()
    + {abstract} IsDone()
    + {abstract} CurrentItem()
}

class ConcreteAggregate {
    + CreateIterator()
}
note bottom of ConcreteAggregate
    return new ConcreteIterator (this)
end note

' relations
ConcreteIterator -up-|> Iterator
ConcreteAggregate -up-|> Aggregate
ConcreteIterator --le> ConcreteAggregate
ConcreteAggregate ..> ConcreteIterator

Client -> Iterator
Client -> Aggregate

@enduml