@startuml
title Iterator Pattern

interface Aggregate {
    + CreateIterator()
}
interface Iterator {
    + First()
    + Next()
    + IsDone()
    + CurrentItem()
}

' relations
ConcreteIterator .up.|> Iterator
ConcreteAggregate .up.|> Aggregate
ConcreteIterator --> ConcreteAggregate
ConcreteAggregate ...> ConcreteIterator : create >

Client -> Aggregate
Client ---> Iterator

@enduml