@startuml
title Iterator Pattern

interface Aggregate  {
    iterator
}
note right
    Represents aggregation
end note

class BookShelf {
    books
    last
    getBookAt()
    appendBook()
    getLength()
    iterator()
}

class Book {
    name
    getName()
}

interface Iterator {
    hasNext()
    next()
}
note right
    Count up and scan
end note

class BookShelfIterator {
    BookShelf
    index
    hasNext()
    next()
}

' relations
BookShelf .|> Aggregate
BookShelf o-le-> Book

Aggregate --> Iterator : create

BookShelfIterator .|> Iterator
BookShelfIterator o--> BookShelf

@enduml